import type { WysiwygTheme } from '../../shared/pathUtils';
import { ACME_PALETTE as A } from '../../shared/acmePalette';
import { SOURCE_DARK_PALETTE as P } from '../../shared/sourceDarkPalette';

/** 与 WYSIWYG dark.css / cm6-theme-basic-dark 保持一致 */
export const MERMAID_DARK_THEME_VARIABLES = {
  darkMode: true,
  background: P.bg,
  mainBkg: P.surface,
  secondaryColor: '#35393d',
  tertiaryColor: P.border,
  primaryColor: P.surface,
  primaryTextColor: P.fg,
  primaryBorderColor: '#484c50',
  secondaryTextColor: P.fg,
  secondaryBorderColor: '#484c50',
  tertiaryTextColor: P.muted,
  tertiaryBorderColor: P.border,
  lineColor: P.muted,
  textColor: P.fg,
  titleColor: P.heading,
  nodeBkg: P.surface,
  nodeBorder: '#484c50',
  clusterBkg: '#252a2e',
  clusterBorder: P.border,
  defaultLinkColor: P.link,
  edgeLabelBackground: P.surface,
  actorBkg: P.surface,
  actorBorder: '#484c50',
  actorTextColor: P.fg,
  actorLineColor: P.muted,
  signalColor: P.muted,
  signalTextColor: P.fg,
  labelBoxBkgColor: '#35393d',
  labelBoxBorderColor: '#484c50',
  labelTextColor: P.fg,
  loopTextColor: P.muted,
  noteBkgColor: '#35393d',
  noteBorderColor: '#484c50',
  noteTextColor: P.fg,
  activationBkgColor: P.border,
  activationBorderColor: '#484c50',
  sequenceNumberColor: P.heading,
  sectionBkgColor: P.surface,
  altSectionBkgColor: '#252a2e',
  gridColor: P.border,
  taskBkgColor: '#35393d',
  taskTextColor: P.fg,
  taskBorderColor: '#484c50',
  activeTaskBkgColor: P.border,
  doneTaskBkgColor: P.surface,
  critBkgColor: '#450a0a',
  critBorderColor: '#7f1d1d',
  todayLineColor: P.accent,
  pieStrokeColor: P.bg,
  pieLegendTextColor: P.fg,
  pieTitleTextColor: P.heading,
  pieSectionTextColor: P.heading,
  git0: P.accent,
  git1: '#34d399',
  git2: '#fbbf24',
  git3: '#f87171',
  git4: '#a78bfa',
  git5: '#fb923c',
  git6: '#22d3ee',
  git7: '#f472b6',
  gitBranchLabel0: P.fg,
  gitBranchLabel1: P.fg,
  gitBranchLabel2: P.fg,
  gitBranchLabel3: P.fg,
  commitLabelColor: P.fg,
  commitLabelBackground: P.surface,
} as const;

/** 与 WYSIWYG acme.css 保持一致 */
export const MERMAID_ACME_THEME_VARIABLES = {
  darkMode: false,
  background: A.bg,
  mainBkg: A.header,
  secondaryColor: A.codeBg,
  tertiaryColor: A.border,
  primaryColor: A.header,
  primaryTextColor: A.fg,
  primaryBorderColor: A.border,
  secondaryTextColor: A.fg,
  secondaryBorderColor: A.border,
  tertiaryTextColor: A.muted,
  tertiaryBorderColor: A.border,
  lineColor: A.fg,
  textColor: A.fg,
  titleColor: A.fg,
  nodeBkg: A.header,
  nodeBorder: A.border,
  clusterBkg: A.codeBg,
  clusterBorder: A.border,
  defaultLinkColor: A.link,
  edgeLabelBackground: A.bg,
  actorBkg: A.header,
  actorBorder: A.border,
  actorTextColor: A.fg,
  actorLineColor: A.fg,
  signalColor: A.fg,
  signalTextColor: A.fg,
  labelBoxBkgColor: A.header,
  labelBoxBorderColor: A.border,
  labelTextColor: A.fg,
  loopTextColor: A.muted,
  noteBkgColor: A.codeBg,
  noteBorderColor: A.border,
  noteTextColor: A.fg,
  activationBkgColor: A.selection,
  activationBorderColor: A.border,
  sequenceNumberColor: A.fg,
  sectionBkgColor: A.header,
  altSectionBkgColor: A.codeBg,
  gridColor: A.border,
  taskBkgColor: A.header,
  taskTextColor: A.fg,
  taskBorderColor: A.border,
  activeTaskBkgColor: A.selection,
  doneTaskBkgColor: A.codeBg,
  critBkgColor: A.bg,
  critBorderColor: '#cc0000',
  todayLineColor: A.accent,
  pieStrokeColor: A.border,
  pieLegendTextColor: A.fg,
  pieTitleTextColor: A.fg,
  pieSectionTextColor: A.fg,
  git0: A.accent,
  git1: '#006400',
  git2: '#800080',
  git3: '#cc0000',
  git4: '#000080',
  git5: '#804000',
  git6: '#008080',
  git7: '#800080',
  gitBranchLabel0: A.fg,
  gitBranchLabel1: A.fg,
  gitBranchLabel2: A.fg,
  gitBranchLabel3: A.fg,
  commitLabelColor: A.fg,
  commitLabelBackground: A.header,
} as const;

export type MermaidInitConfig = {
  startOnLoad: boolean;
  securityLevel: 'strict';
  theme: 'neutral' | 'base';
  themeVariables?:
    | typeof MERMAID_DARK_THEME_VARIABLES
    | typeof MERMAID_ACME_THEME_VARIABLES;
};

export function getMermaidInitConfig(theme: WysiwygTheme): MermaidInitConfig {
  if (theme === 'dark') {
    return {
      startOnLoad: false,
      securityLevel: 'strict',
      theme: 'base',
      themeVariables: MERMAID_DARK_THEME_VARIABLES,
    };
  }
  if (theme === 'acme') {
    return {
      startOnLoad: false,
      securityLevel: 'strict',
      theme: 'base',
      themeVariables: MERMAID_ACME_THEME_VARIABLES,
    };
  }
  return {
    startOnLoad: false,
    securityLevel: 'strict',
    theme: 'neutral',
  };
}
